# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "users", :force => true do |t|
    t.column "username",        :string,   :limit => 20
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "nomecompleto",    :string,   :limit => 50
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

end
