# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "programs", :force => true do |t|
    t.column "user_id",    :integer,               :null => false
    t.column "nome",       :string,  :limit => 20
    t.column "descricao",  :string,  :limit => 50
    t.column "codigo",     :text
    t.column "parametros", :text
  end

  create_table "users", :force => true do |t|
    t.column "username",        :string,   :limit => 20
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "nomecompleto",    :string,   :limit => 50
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

end
